import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { LineChart, Line, XAxis, YAxis, Tooltip, ResponsiveContainer, RadarChart, PolarGrid, PolarAngleAxis, Radar } from 'recharts';
import { analyze, demoData, narrative } from './lib/api';
import { db } from './lib/db';
import { CognitiveSession } from './types/session';
import './style.css';

function uuid(){ return localStorage.getItem('anon') ?? (localStorage.setItem('anon', crypto.randomUUID()), localStorage.getItem('anon')!); }
function empty(): CognitiveSession { return { anonymous_id: uuid(), session_date: new Date().toISOString(), sleep_quality:7, stress:4, alertness:6, digit_span:7, reaction_time_ms:280, stroop_accuracy:.85, stroop_interference_ms:120, notes:'', opt_in_sync:false }; }
function useTimer(){ const [start,setStart]=useState(0); return { begin:()=>requestAnimationFrame(()=>setStart(performance.now())), elapsed:()=>performance.now()-start }; }
function Tests({onSession}:{onSession:(s:Partial<CognitiveSession>)=>void}){ const timer=useTimer(); const [msg,setMsg]=useState('Press Start'); const [rts,setRts]=useState<number[]>([]); function startRt(){ setMsg('Wait for green'); setTimeout(()=>{timer.begin(); setMsg('GO - press Space');},700+Math.random()*1200); } useEffect(()=>{ const h=(e:KeyboardEvent)=>{ if(e.code==='Space' && msg.startsWith('GO')){ const rt=timer.elapsed(); const next=[...rts,rt]; setRts(next); if(next.length>=5){ onSession({reaction_time_ms: next.reduce((a,b)=>a+b,0)/next.length}); setMsg('Reaction test saved'); setRts([]); } else startRt(); }}; window.addEventListener('keydown',h); return()=>window.removeEventListener('keydown',h); },[msg,rts]); return <div className="card"><h2>Cognitive Tests</h2><button onClick={startRt}>Simple Reaction Time</button><p>{msg}</p><button onClick={()=>onSession({digit_span: Math.round(5+Math.random()*5)})}>Digit Span adaptive demo</button><button onClick={()=>onSession({stroop_accuracy:.75+Math.random()*.2, stroop_interference_ms:80+Math.random()*90})}>Stroop keyboard demo</button><p>Tests use performance.now(), keyboard input, and requestAnimationFrame for timing-critical starts.</p></div>; }
function App(){ const [sessions,setSessions]=useState<CognitiveSession[]>([]); const [draft,setDraft]=useState<CognitiveSession>(empty()); const [analysis,setAnalysis]=useState<any>(); const [story,setStory]=useState(''); useEffect(()=>{db.sessions.toArray().then(setSessions);},[]); async function save(){ const s={...draft, session_date:new Date().toISOString()}; await db.sessions.add(s); const all=await db.sessions.toArray(); setSessions(all); setDraft(empty()); } async function loadDemo(){ const rows=await demoData(); await db.sessions.clear(); await db.sessions.bulkAdd(rows); setSessions(await db.sessions.toArray()); } async function runAnalyze(){ setAnalysis(await analyze(sessions)); } async function runNarrative(){ setStory((await narrative(sessions)).narrative); } const chart=sessions.map((s,i)=>({i, rt:s.reaction_time_ms, span:s.digit_span, stroop:s.stroop_accuracy*100})); const radar=analysis?Object.entries(analysis.domain_scores).map(([k,v])=>({domain:k, score:v as number})):[]; return <main><h1>Neurocognitive Mirror</h1><p>Local-first cognitive analytics. Raw event streams remain in the browser unless you export them.</p><div className="grid"><section className="card"><h2>Self Report</h2>{(['sleep_quality','stress','alertness'] as const).map(k=><label key={k}>{k}<input type="range" min="1" max="10" step=".1" value={draft[k]} onChange={e=>setDraft({...draft,[k]:Number(e.target.value)})}/>{draft[k]}</label>)}<textarea placeholder="notes" value={draft.notes} onChange={e=>setDraft({...draft,notes:e.target.value})}/><button onClick={save}>Save local session</button><button onClick={loadDemo}>Load demo mode</button></section><Tests onSession={p=>setDraft({...draft,...p})}/></div><div className="card"><h2>Dashboard</h2><button disabled={!sessions.length} onClick={runAnalyze}>Analyze</button><button disabled={!sessions.length} onClick={runNarrative}>Narrative</button><ResponsiveContainer width="100%" height={260}><LineChart data={chart}><XAxis dataKey="i"/><YAxis/><Tooltip/><Line dataKey="rt" stroke="#ef4444"/><Line dataKey="span" stroke="#3b82f6"/><Line dataKey="stroop" stroke="#22c55e"/></LineChart></ResponsiveContainer>{radar.length>0&&<ResponsiveContainer width="100%" height={260}><RadarChart data={radar}><PolarGrid/><PolarAngleAxis dataKey="domain"/><Radar dataKey="score" fill="#6366f1" fillOpacity={0.4}/></RadarChart></ResponsiveContainer>}<pre>{analysis?JSON.stringify(analysis,null,2):'No analysis yet'}</pre><article>{story}</article></div></main>; }

createRoot(document.getElementById('root')!).render(<App />);
